title: Megha Mehta
logo: # You can add own logo. For example '/images/logo.png'.
description: Melotta is a modern and minimal Jekyll theme for sharing your ideas.

# Author Settings
author:
  name: Megha Mehta
  image: "/images/01.jpg"

contact:
  - {
      name: "Facebook",
      icon: "ion-logo-facebook",
      link: "https://www.facebook.com/mehta.megz",
    }
  - {
      name: "Instagram",
      icon: "ion-logo-instagram",
      link: "https://www.instagram.com/megz_mehta/",
    }
  - { name: "Email", icon: "ion-ios-mail", link: "mailto:mehta.megz@gmail.com" }

# Slider Section
slider: Life # NOTE - By default, the slider is set to display tags. Now the slider shows the tag with the text "Life". If you do not want to use the slider, leave the slider field empty.

# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: https://www.instagram.com/megz_mehta/
userID: 6716400487
accessToken: 6716400487.1677ed0.4fae51c47bc544a895b81756a7d0c477

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

